### ISSUE TITLE
Traduzione errori di PWS

### ISSUE THREAD

**Issue by lucach** [veluca93/oii-web#31]
Al momento, tutte le stringhe ritornate da PWS ([esempio](https://github.com/veluca93/oii-web/blob/master/cms/server/PracticeWebServer.py#L762)) sono inviate a NotificationHub senza essere tradotte ([esempio](https://github.com/veluca93/oii-web/blob/master/cms/web/practice/js/task.js#L214)).

Un'osservazione: c'è un motivo per cui non inviamo le stringhe a notificationHub in inglese e le traduciamo lì prima di visualizzarle (evitando così errori come quello che ho indicato)?

**Comment by wil93** [comment]
> c'è un motivo per cui non inviamo le stringhe a notificationHub in inglese e le traduciamo lì prima di visualizzarle (evitando così errori come quello che ho indicato)?

A pensarci bene no. Cioè, `notificationHub` vorrebbe essere "generico" nel senso che si può in teoria usare anche per fare debug (quindi quasi sicuramente la stringa che gli passo non ha una traduzione)... tuttavia se la stringa non ha traduzione la restituiamo così com'è quindi non dovrebbero esserci problemi.
